-- AmPro: rename role label 'dancer' -> 'user' (keep admin as-is)

-- 1) Migrate existing rows
update public.ampro_user_roles
set role = 'user'
where role = 'dancer';

-- 2) Ensure role constraint matches the new label.
-- We don't know the autogenerated constraint name on existing DBs, so we drop any
-- CHECK constraint that contains "role in ('admin', 'dancer')" and recreate it.
DO $$
DECLARE
  cname text;
BEGIN
  SELECT c.conname
  INTO cname
  FROM pg_constraint c
  WHERE c.conrelid = 'public.ampro_user_roles'::regclass
    AND c.contype = 'c'
    AND pg_get_constraintdef(c.oid) ILIKE '%role in (%admin%'
    AND pg_get_constraintdef(c.oid) ILIKE '%dancer%';

  IF cname IS NOT NULL THEN
    EXECUTE format('alter table public.ampro_user_roles drop constraint %I', cname);
  END IF;

  -- Add the expected constraint if missing
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c2
    WHERE c2.conrelid = 'public.ampro_user_roles'::regclass
      AND c2.contype = 'c'
      AND pg_get_constraintdef(c2.oid) ILIKE '%role in (%admin%'
      AND pg_get_constraintdef(c2.oid) ILIKE '%user%'
  ) THEN
    ALTER TABLE public.ampro_user_roles
      ADD CONSTRAINT ampro_user_roles_role_check
      CHECK (role IN ('admin', 'user'));
  END IF;
END $$;
